### ISSUE TITLE
relevance-ranked search in user interface 

### ISSUE THREAD

**Issue by ifrojdo** [msainio/plague-inc#26]
we need to incorporate our search engine in to this weeks code. as of now, the user interface search engine is very simple (if query=entry in list, matches.append) ~ish so this needs to be changed for our own thingy. it would be good if we could decide on doing either relevance ranked or boolean too? but i'm suggesting we do RR and then rank the results according to their scores.

**Comment by annikarantala** [comment]
I vote relevance-ranked too, seems nicer

**Comment by ifrojdo** [comment]
at this point i've gotten some of the code working. the ranked search produces a list of dictionaries called "matches", which is then pushed on to the plague.html file. 
The final user interface still isn't working :( i believe the issue is caused by the list. the code isn't able to read the dictionary elements like it is supposed to.

could someone check it out?
